### data
smiles_col: "SMILES"
target_col_prefix: "TARGET"
target_normalize: "auto"
anomaly_clean: True
smi_strict: False
### model
model_name: "unimolv1"
### trainer
split_method: "5fold_random" 
split_seed: 42
seed: 42
logger_level: 1
patience: 10
max_epochs: 100
learning_rate: 1e-4
warmup_ratio: 0.03
batch_size: 16
max_norm: 5.0
cuda: True
amp: True
